syntax on
filetype on
filetype plugin on "启用文件类型插件
set nocompatible
set mouse=c
set expandtab
set softtabstop=4
set shiftwidth=4
set autoindent
set nobackup
set nowritebackup
set noswapfile
set encoding=utf-8
highlight LineNr ctermfg=250 guifg=#BBBBBB
